services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "1337:1337"
    depends_on:
      - postgres
    environment:
      # DATABASE_URL: ${DATABASE_URL}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}
      NODE_ENV: production
      PUBLIC_URL: https://admin.christophergalea.com
      STRAPI_ADMIN_BACKEND_URL:

  # PostgreSQL Database Service
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data2:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data2:
